BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.stopGroups
	(
	id int NOT NULL IDENTITY (1, 1),
	groupName nvarchar(50) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.stopGroups ADD CONSTRAINT
	PK_stopGroups PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.stopGroups SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/****** Object:  Table [dbo].[stopGroupStops]    Script Date: 13/12/2016 21:41:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stopGroupStops](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[stopGroupId] [int] NOT NULL,
	[stopId] [int] NOT NULL,
 CONSTRAINT [PK_stopGroupStops] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [dbo].[stopGroupStops]  WITH CHECK ADD  CONSTRAINT [FK_stopGroup] FOREIGN KEY(stopGroupId)
REFERENCES [dbo].[stopGroups] ([id])
GO

ALTER TABLE [dbo].[stopGroupStops]  WITH CHECK ADD  CONSTRAINT [FK_stopGroupStopIds] FOREIGN KEY([stopId])
REFERENCES [dbo].[busStops] (stopNumber)
GO

